In [117]:
#pip install networkx
#pip install scipy
#pip install principal-feature-analysis
#pip install pandas

In [118]:
from principal_feature_analysis import pfa 
import pandas as pd

In [119]:
!pwd

/home2/lumpi/Projects/single-cell_samantha/code/scripts

# Run PFA

In [ ]:
# test how the pfa read the data (somehow the label row gets processed)
path="/home2/lumpi/Projects/single-cell_samantha/data/PFA_analysis_data.csv"
data = pd.read_csv(path, sep=',', header=None)
data

In [120]:
res,mutual_information=pfa(path="/home2/lumpi/Projects/single-cell_samantha/data/PFA_analysis_data.csv", calculate_mutual_information=True,
                           cluster_size=200, min_n_datapoints_a_bin=50)

Sweep number: 1
Feature #5 has only constant values
Feature #9 has only constant values
Feature #12 has only constant values
Feature #34 has only constant values
Feature #56 has only constant values
Feature #59 has only constant values
Feature #69 has only constant values
Feature #71 has only constant values
Feature #91 has only constant values
Feature #99 has only constant values
Feature #130 has only constant values
Feature #145 has only constant values
Feature #164 has only constant values
Feature #190 has only constant values
Feature #195 has only constant values
Feature #196 has only constant values
Feature #197 has only constant values
Feature #200 has only constant values
Feature #201 has only constant values
Feature #213 has only constant values
Feature #214 has only constant values
Feature #215 has only constant values
Feature #223 has only constant values
Feature #249 has only constant values
Feature #270 has only constant values
Feature #295 has only constant values
Feature #376 has only constant values
Feature #395 has only constant values
Feature #401 has only constant values
Feature #415 has only constant values
Feature #421 has only constant values
Feature #428 has only constant values
Feature #429 has only constant values
Feature #438 has only constant values
Feature #440 has only constant values
Feature #442 has only constant values
Feature #445 has only constant values
Feature #460 has only constant values
Feature #467 has only constant values
Feature #470 has only constant values
Feature #479 has only constant values
Feature #484 has only constant values
Feature #488 has only constant values
Feature #506 has only constant values
Feature #534 has only constant values
Feature #551 has only constant values
Feature #573 has only constant values
Feature #602 has only constant values
Feature #606 has only constant values
Feature #623 has only constant values
Feature #631 has only constant values
Feature #651 has only constant values
Feature #682 has only constant values
Feature #693 has only constant values
Feature #728 has only constant values
Feature #733 has only constant values
Feature #746 has only constant values
Feature #760 has only constant values
Feature #761 has only constant values
Feature #776 has only constant values
Feature #799 has only constant values
Feature #827 has only constant values
Feature #828 has only constant values
Feature #844 has only constant values
Feature #846 has only constant values
Feature #863 has only constant values
Feature #881 has only constant values
Feature #888 has only constant values
Feature #913 has only constant values
Feature #947 has only constant values
Feature #958 has only constant values
Feature #963 has only constant values
Feature #991 has only constant values
Feature #1031 has only constant values
Feature #1037 has only constant values
Feature #1054 has only constant values
Feature #1056 has only constant values
Feature #1060 has only constant values
Feature #1077 has only constant values
Feature #1082 has only constant values
Feature #1107 has only constant values
Feature #1168 has only constant values
Feature #1185 has only constant values
Feature #1191 has only constant values
Feature #1218 has only constant values
Feature #1238 has only constant values
Feature #1265 has only constant values
Feature #1274 has only constant values
Feature #1280 has only constant values
Feature #1287 has only constant values
Feature #1292 has only constant values
Feature #1299 has only constant values
Feature #1343 has only constant values
Feature #1344 has only constant values
Feature #1359 has only constant values
Feature #1362 has only constant values
Feature #1392 has only constant values
Feature #1403 has only constant values
Feature #1408 has only constant values
Feature #1414 has only constant values
Feature #1430 has only constant values
Feature #1449 has only constant values
Feature #1452 has only constant values
Feature #1462 has only constant values
Feature #1468 has only constant values
Feature #1478 has only constant values
Feature #1493 has only constant values
Feature #1532 has only constant values
Feature #1542 has only constant values
Feature #1558 has only constant values
Feature #1571 has only constant values
Feature #1573 has only constant values
Feature #1597 has only constant values
Feature #1602 has only constant values
Feature #1603 has only constant values
Feature #1611 has only constant values
Binning done!
List of features with constant values:
[5, 9, 12, 34, 56, 59, 69, 71, 91, 99, 130, 145, 164, 190, 195, 196, 197, 200, 201, 213, 214, 215, 223, 249, 270, 295, 376, 395, 401, 415, 421, 428, 429, 438, 440, 442, 445, 460, 467, 470, 479, 484, 488, 506, 534, 551, 573, 602, 606, 623, 631, 651, 682, 693, 728, 733, 746, 760, 761, 776, 799, 827, 828, 844, 846, 863, 881, 888, 913, 947, 958, 963, 991, 1031, 1037, 1054, 1056, 1060, 1077, 1082, 1107, 1168, 1185, 1191, 1218, 1238, 1265, 1274, 1280, 1287, 1292, 1299, 1343, 1344, 1359, 1362, 1392, 1403, 1408, 1414, 1430, 1449, 1452, 1462, 1468, 1478, 1493, 1532, 1542, 1558, 1571, 1573, 1597, 1602, 1603, 1611]
Starting principal feature analysis!
Nodes left: 1499
6 nodes removed!
9 nodes removed!
8 nodes removed!
10 nodes removed!
10 nodes removed!
10 nodes removed!
15 nodes removed!
15 nodes removed!
10 nodes removed!
3 nodes removed!
15 nodes removed!
4 nodes removed!
3 nodes removed!
5 nodes removed!
5 nodes removed!
7 nodes removed!
9 nodes removed!
7 nodes removed!
9 nodes removed!
20 nodes removed!
16 nodes removed!
6 nodes removed!
10 nodes removed!
5 nodes removed!
5 nodes removed!
7 nodes removed!
8 nodes removed!
12 nodes removed!
13 nodes removed!
19 nodes removed!
15 nodes removed!
20 nodes removed!
4 nodes removed!
8 nodes removed!
7 nodes removed!
9 nodes removed!
13 nodes removed!
13 nodes removed!
13 nodes removed!
26 nodes removed!
14 nodes removed!
22 nodes removed!
2 nodes removed!
4 nodes removed!
9 nodes removed!
7 nodes removed!
11 nodes removed!
10 nodes removed!
34 nodes removed!
15 nodes removed!
8 nodes removed!
3 nodes removed!
6 nodes removed!
2 nodes removed!
1 nodes removed!
3 nodes removed!
4 nodes removed!
9 nodes removed!
19 nodes removed!
14 nodes removed!
10 nodes removed!
15 nodes removed!
10 nodes removed!
12 nodes removed!
6 nodes removed!
2 nodes removed!
5 nodes removed!
5 nodes removed!
4 nodes removed!
8 nodes removed!
7 nodes removed!
17 nodes removed!
16 nodes removed!
12 nodes removed!
8 nodes removed!
5 nodes removed!
5 nodes removed!
2 nodes removed!
2 nodes removed!
2 nodes removed!
5 nodes removed!
6 nodes removed!
5 nodes removed!
5 nodes removed!
8 nodes removed!
5 nodes removed!
2 nodes removed!
Nodes left: 704
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
2 nodes removed!
2 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
2 nodes removed!
Nodes left: 672
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
Nodes left: 668
Nodes left: 668
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
2 nodes removed!
1 nodes removed!
2 nodes removed!
2 nodes removed!
2 nodes removed!
2 nodes removed!
1 nodes removed!
2 nodes removed!
2 nodes removed!
2 nodes removed!
2 nodes removed!
2 nodes removed!
2 nodes removed!
2 nodes removed!
2 nodes removed!
1 nodes removed!
1 nodes removed!
1 nodes removed!
2 nodes removed!
2 nodes removed!
1 nodes removed!
Nodes left: 627
Dissection done!
principal features:
[[1], [2], [3], [4], [7], [8], [10], [11], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23], [24], [25], [26], [28], [29], [30], [31], [32], [33], [35], [37], [38], [39], [40], [42], [43], [44], [45], [46], [48], [49], [50], [51], [52], [53], [54], [55], [57], [58], [60], [61], [62], [63], [64], [65], [66], [67], [68], [70], [72], [73], [74], [75], [76], [77], [78], [79], [80], [81], [82], [83], [85], [87], [88], [90], [92], [94], [95], [97], [98], [100], [101], [102], [103], [104], [105], [106], [107], [108], [109], [111], [113], [114], [115], [116], [117], [118], [119], [120], [121], [122], [123], [124], [125], [126], [127], [128], [129], [131], [132], [133], [134], [135], [136], [137], [138], [139], [140], [141], [143], [144], [146], [147], [148], [149], [150], [151], [152], [153], [154], [155], [156], [157], [158], [160], [161], [162], [163], [165], [166], [167], [168], [170], [171], [172], [174], [175], [176], [177], [178], [179], [180], [181], [182], [183], [185], [187], [188], [189], [191], [192], [193], [194], [198], [199], [202], [203], [204], [205], [206], [207], [209], [210], [211], [212], [216], [217], [218], [219], [220], [221], [222], [224], [225], [226], [227], [228], [229], [230], [231], [232], [233], [234], [235], [236], [237], [238], [239], [240], [241], [242], [244], [245], [248], [250], [251], [252], [253], [254], [255], [256], [257], [258], [259], [260], [262], [263], [264], [265], [266], [267], [268], [269], [271], [272], [273], [274], [276], [277], [278], [279], [280], [281], [282], [283], [284], [285], [286], [287], [288], [289], [290], [291], [292], [293], [294], [296], [297], [299], [300], [301], [302], [303], [305], [306], [307], [308], [309], [310], [311], [313], [314], [315], [316], [317], [319], [320], [321], [322], [324], [325], [326], [327], [328], [329], [330], [331], [332], [334], [335], [336], [337], [338], [339], [340], [341], [342], [343], [344], [345], [347], [348], [349], [350], [351], [352], [353], [354], [355], [356], [358], [359], [360], [361], [363], [364], [366], [367], [368], [369], [370], [371], [372], [373], [375], [377], [378], [379], [380], [381], [382], [383], [384], [385], [386], [387], [388], [389], [390], [391], [392], [394], [396], [397], [398], [399], [402], [403], [404], [405], [406], [408], [409], [410], [411], [412], [413], [414], [416], [417], [418], [419], [420], [422], [423], [424], [425], [426], [427], [430], [431], [432], [433], [434], [436], [437], [439], [441], [443], [444], [446], [447], [448], [449], [450], [451], [452], [453], [454], [455], [456], [457], [458], [459], [462], [463], [464], [465], [466], [468], [469], [471], [472], [473], [474], [475], [476], [477], [478], [480], [481], [482], [483], [485], [486], [487], [489], [490], [491], [492], [493], [494], [495], [496], [498], [499], [500], [501], [502], [504], [505], [507], [508], [509], [511], [512], [513], [514], [515], [516], [517], [518], [519], [520], [521], [523], [524], [525], [526], [527], [528], [530], [531], [532], [533], [535], [536], [537], [538], [539], [540], [541], [542], [543], [545], [547], [548], [549], [552], [553], [554], [557], [558], [559], [560], [562], [563], [564], [565], [566], [567], [568], [569], [570], [571], [572], [574], [575], [576], [577], [578], [579], [580], [581], [582], [583], [584], [585], [586], [587], [588], [589], [591], [592], [593], [594], [595], [596], [597], [598], [599], [600], [601], [603], [604], [605], [607], [608], [609], [610], [612], [613], [614], [615], [616], [617], [618], [619], [620], [621], [622], [624], [625], [626], [627], [628], [629], [630], [632], [633], [634], [635], [636], [637], [638], [639], [640], [641], [642], [644], [645], [646], [647], [648], [649], [650], [652], [653], [654], [655], [656], [657], [658], [659], [660], [661], [663], [664], [666], [671], [672], [673], [676], [677], [679], [680], [681], [684], [685], [686], [687], [688], [689], [691], [692], [694], [695], [696], [697], [698], [699], [700], [701], [702], [704], [705], [706], [708], [709], [712], [713], [714], [715], [716], [717], [718], [719], [721], [722], [611], [503], [643], [556], [546], [298], [346], [365], [6], [561], [304], [400], [544], [246], [243], [275, 96], [323], [110], [27], [550], [522, 675], [318, 720], [683], [662], [710], [247], [529]]
Start calculating dependence on system state
Ambiguous complete subgraph:
List with features depending on system state:
[675]
List with features not depending on system state:
[522]
Ambiguous complete subgraph:
List with features depending on system state:
[720]
List with features not depending on system state:
[318]
principal features depending on system state:
[[1], [3], [7], [10], [11], [14], [16], [18], [21], [23], [24], [25], [28], [29], [30], [31], [32], [33], [35], [46], [48], [49], [50], [51], [52], [55], [60], [61], [64], [65], [66], [67], [72], [74], [76], [77], [78], [79], [80], [81], [82], [83], [85], [88], [95], [100], [103], [105], [106], [107], [108], [111], [114], [120], [122], [123], [124], [125], [128], [131], [133], [134], [135], [137], [138], [140], [147], [148], [149], [150], [152], [153], [155], [157], [162], [163], [165], [166], [167], [168], [172], [175], [178], [179], [180], [181], [182], [183], [188], [189], [194], [203], [205], [206], [211], [212], [217], [221], [222], [224], [225], [227], [231], [234], [236], [239], [240], [242], [245], [248], [250], [253], [255], [259], [264], [265], [266], [268], [271], [272], [278], [281], [282], [283], [284], [286], [287], [291], [292], [299], [300], [302], [305], [306], [307], [309], [314], [316], [317], [320], [324], [325], [326], [327], [329], [330], [334], [336], [338], [340], [341], [342], [344], [347], [348], [350], [352], [356], [358], [366], [367], [368], [369], [373], [377], [378], [379], [381], [382], [383], [387], [388], [389], [392], [394], [398], [402], [404], [410], [412], [413], [418], [419], [420], [422], [424], [426], [432], [433], [434], [436], [437], [446], [448], [450], [451], [452], [453], [455], [456], [457], [462], [463], [465], [466], [468], [475], [476], [477], [481], [483], [485], [486], [490], [491], [492], [493], [494], [496], [498], [500], [501], [502], [505], [507], [508], [509], [511], [512], [513], [514], [516], [517], [518], [519], [521], [524], [526], [527], [528], [536], [537], [538], [540], [541], [543], [547], [548], [557], [560], [562], [563], [564], [565], [566], [568], [569], [570], [571], [572], [574], [575], [576], [579], [583], [587], [589], [597], [598], [601], [604], [605], [607], [608], [610], [613], [616], [617], [620], [621], [624], [625], [627], [628], [630], [632], [633], [635], [637], [639], [641], [642], [645], [646], [647], [648], [650], [652], [653], [654], [656], [658], [659], [660], [661], [663], [672], [676], [677], [679], [680], [685], [686], [689], [692], [695], [699], [700], [702], [704], [705], [706], [708], [709], [714], [715], [716], [722], [611], [643], [556], [546], [365], [561], [400], [246], [243], [110], [27], [675, '*', 522], [720, '*', 318], [662], [247], [529]]
100.0% of the chi-square test for the adjacency matrix have been performed with a bin less than 5 data points!
88.50735557947614% of the chi-square test for the adjacency matrix have been performed with a bin less than 1 data points!
0.0% of the chi-square test for finding the relevant principal features have been performed with a bin less than 5 data points!
0.0% of the chi-square test for finding the relevant principal features have been performed with a bin less than 1 data points!
Time needed for the PFA in seconds: 128.08970665931702
Calculating mutual information
     index feature  mutual information
0                0            0.794272
1                1            0.161720
2                3            0.007816
3                7            0.005133
4               10            0.343983
..             ...                 ...
342            720            0.670917
343            318            0.000000
344            662            0.014447
345            247            0.203145
346            529            0.090863

[347 rows x 2 columns]

In [124]:
mutual_information_bu=mutual_information
mutual_information

     index feature  mutual information
0                0            0.794272
1                1            0.161720
2                3            0.007816
3                7            0.005133
4               10            0.343983
..             ...                 ...
342            720            0.670917
343            318            0.000000
344            662            0.014447
345            247            0.203145
346            529            0.090863

[347 rows x 2 columns]

In [ ]:
mutual_information=mutual_information[0]

In [126]:
# correct the index of mutual information
mutual_information = mutual_information.drop(mutual_information.index[0])
mutual_information

     index feature  mutual information
1                1            0.161720
2                3            0.007816
3                7            0.005133
4               10            0.343983
5               11            0.007991
..             ...                 ...
342            720            0.670917
343            318            0.000000
344            662            0.014447
345            247            0.203145
346            529            0.090863

[346 rows x 2 columns]

In [129]:
mutual_information['index feature'] = mutual_information['index feature'] - 1
mutual_information

     index feature  mutual information
1                0            0.161720
2                2            0.007816
3                6            0.005133
4                9            0.343983
5               10            0.007991
..             ...                 ...
342            719            0.670917
343            317            0.000000
344            661            0.014447
345            246            0.203145
346            528            0.090863

[346 rows x 2 columns]

In [ ]:
## correct res index
#type(res)
# Delete the first element of list 'res'
#del res[0]

# Subtract 1 from each element in the list
#res = [x - 1 for x in res]
#res

In [139]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')

In [137]:
gene_names=gene_names.iloc[res,:].reset_index(drop=True)

In [154]:
gene_names.iloc[467]

gene_names    MYO10
Name: 467, dtype: object

In [158]:
#to correct wrong joining
#mutual_information = mutual_information.drop(columns=['gene_names'])
gene_names

     gene_names
0          HES4
1         ISG15
2      C1QTNF12
3       TNFRSF9
4     LINC01647
...         ...
1610      PNMA5
1611        BGN
1612     ATP2B3
1613      L1CAM
1614     MT-CO2

[1615 rows x 1 columns]

In [ ]:
# refine the block where combining mutual information

In [177]:
mutual_information = mutual_information.drop(columns=['gene_names'])

In [173]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')

# Set index for gene_names DataFrame to match the join operation requirement
gene_names.index = range(gene_names.shape[0])  # Assuming gene_names DataFrame should match indices as given
joined_df = mutual_information.join(gene_names, on='index feature', how='left')
joined_df.sort_values(by=["mutual information"], ascending=False)

     index feature  mutual information gene_names
238            525            0.751974      TGFBI
239            526            0.708558     SPOCK1
342            719            0.670917   SERPINE1
217            492            0.575607    ADAMTS6
206            467            0.526202      MYO10
..             ...                 ...        ...
215            490            0.002012      PDE4D
223            501            0.001885      EDIL3
265            582            0.001219       H1-5
341            521            0.000000       FBN2
343            317            0.000000  LINC00971

[346 rows x 3 columns]

In [178]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')
#gene_names=gene_names.iloc[res,:].reset_index(drop=True)
gene_names.index = range(gene_names.shape[0])

#it seem like this join doenst make sense. mutal information should join via index feature with gene names. 
#or the index of mutal information should be the index feature (correct that)
#mutual_information = mutual_information.drop(columns=['gene_names'])
#mutual_information=mutual_information.join(gene_names)
mutual_information = mutual_information.join(gene_names, on='index feature', how='left')


mutual_information_sorted=mutual_information.sort_values(by=["mutual information"], ascending=False)
mutual_information_sorted.to_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_mutual_information.csv', index=False)

f = open("principal_features_for_model.txt", "w")
for i in res:
    f.write(str(i)+str(","))
f.close()

In [180]:
mutual_information_sorted.head(20)

     index feature  mutual information gene_names
238            525            0.751974      TGFBI
239            526            0.708558     SPOCK1
342            719            0.670917   SERPINE1
217            492            0.575607    ADAMTS6
206            467            0.526202      MYO10
259            570            0.490800       SOX4
285            629            0.486788     MARCKS
57             123            0.485984       NAV1
236            520            0.468442        LOX
248            547            0.449390     ADAM19
41              81            0.444531    S100A11
75             161            0.441493     MBOAT2
112            252            0.429763        FN1
314            688            0.406989     IGFBP3
242            536            0.391299       FGF1
266            586            0.376263       IER3
177            401            0.362033     IGFBP7
272            604            0.361966      VEGFA
4                9            0.343983      MFAP2
154            346            0.326507      PLOD2

In [115]:
res[1:10]

[2, 6, 9, 10, 13, 15, 17, 20, 22]

In [42]:
mutual_information_sorted

     index feature  mutual information  gene_names
0                0            0.794272        HES4
238            526            0.751974      SPOCK1
239            527            0.708558        EGR1
342            720            0.670917  LHFPL3-AS2
217            493            0.575607       MAST4
..             ...                 ...         ...
215            491            0.002012      ZSWIM6
223            502            0.001885    EDIL3-DT
265            583            0.001219      SCAND3
341            522            0.000000     SLC27A6
343            318            0.000000       CADM2

[347 rows x 3 columns]

In [48]:
print(mutual_information_sorted[:20])

     index feature  mutual information  gene_names
0                0            0.794272        HES4
238            526            0.751974      SPOCK1
239            527            0.708558        EGR1
342            720            0.670917  LHFPL3-AS2
217            493            0.575607       MAST4
206            468            0.526202   LINC02223
259            571            0.490800      CASC15
285            630            0.486788       VGLL2
57             124            0.485984    IPO9-AS1
236            521            0.468442        FBN2
248            548            0.449390       PTTG1
41              82            0.444531      S100A4
75             162            0.441493        RRM2
112            253            0.429763   LINC00607
314            689            0.406989        TNS3
242            537            0.391299      KCTD16
266            587            0.376263   LINC00243
177            402            0.362033        HTN3
272            605            0.361966   LINC02537
4               10            0.343983       PADI2

## Test if index values are correct

### Of the gene List

In [57]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')

In [60]:
gene_names.shape

(1615, 1)

In [187]:
## ## Validate smae location of gene_names and gene name
gene_names.iloc[468]

gene_names    LINC02223
Name: 468, dtype: object

In [ ]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')

In [ ]:
### Of the PFA file

In [181]:
path="/home2/lumpi/Projects/single-cell_samantha/data/PFA_analysis_data.csv"
number_sweeps=10
gene_selection=0 # validate on PFA = 0, random genes = 1 or all genes = 2


data_total=pd.read_csv(path, sep=",", header=None).transpose()

## here read correctly
data=data_total.sample(frac = 0.8)
data_test=data_total.drop(data.index)
data=data.transpose().to_numpy()
data_test=data_test.transpose().to_numpy()
data_total

,0,1,2,3,4,5,6,7,8,9,...,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615
0,0.0,1.583742,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,3.963516
1,0.0,1.817618,0.0,2.106576,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,3.207734
2,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.291329,0.0,0.0,0.0,0.000000,4.121720
3,0.0,1.823131,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.712088,0.0,0.0,0.0,0.712088,4.241672
4,0.0,1.036066,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.646608,0.0,0.0,0.0,0.000000,4.065095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3723,1.0,3.952191,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,4.907056
3724,1.0,1.624724,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.624724,0.0,0.0,0.0,1.962280,3.515007
3725,1.0,0.896253,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.896253,0.0,0.0,0.0,0.896253,4.477613
3726,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.242907,0.0,0.0,0.0,0.000000,4.970865
3727,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,3.875414

In [189]:
data_test

array([[0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        1.        ],
       [1.43464065, 1.03139913, 1.97117901, ..., 3.17817664, 1.97004366,
        2.73304296],
       [0.72563642, 1.03139913, 0.70796478, ..., 0.        , 0.        ,
        1.16697109],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.70796478, ..., 0.        , 0.        ,
        1.16697109],
       [4.63802814, 4.78856754, 4.79134512, ..., 5.11320972, 5.61336994,
        4.75390863]])

In [186]:
df = data_total
#average_values = df.groupby(df.index).mean()
average_values = df.groupby(df.iloc[:, 0]).mean()
average_values.iloc[:, 468]  
## this position (468) is not LINC02223 but MYO10 
## assumed is when PFA tells a position the wrong gene names is assigned. 
## However the validation with this wrong assigned genne names works, indicating that the PFA alogorithm might account for the mismatch in column index)

0
0.0    0.654341
1.0    2.484578
Name: 468, dtype: float64

In [183]:
#gene_names['LINC02223']
gene_names.index[gene_names['gene_names'] == 'LINC02223'].tolist()

[468]

In [74]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')

In [ ]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')
gene_names=gene_names.iloc[res,:].reset_index(drop=True)

mutual_information=mutual_information.join(gene_names)

mutual_information_sorted=mutual_information.sort_values(by=["mutual information"], ascending=False)
mutual_information_sorted.to_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_mutual_information.csv', index=False)

In [80]:
gene_names.iloc[res,:][200:220]

        gene_names
456         SORBS2
457        F11-AS1
462         SNHG18
463         CTNND2
465        OTULINL
466  CTD-2350J17.1
468      LINC02223
475           NPR3
476          RAI14
477          AGXT2
481      LINC00604
483      FGF10-AS1
485          ARL15
486           ESM1
490          PDE4D
491         ZSWIM6
492        ADAMTS6
493          MAST4
494          CD180
496       ARHGEF28

In [99]:
import inspect 
print(inspect.getsource(pfa))

def pfa(path, number_output_functions=1, number_sweeps=1, cluster_size=50, alpha=0.01, min_n_datapoints_a_bin=500, shuffle_feature_numbers=0, frac=1, calculate_mutual_information=0, basis_log_mutual_information=2):
    # pf_ds = principal features related to output functions, pf = all principal features
    start_time=time.time()
    list_pf_ds=[]


    # The csv file's content is an m x n Matrix with m - number components of output-function = number features and n = number of data points
    # where the first number components of output-function rows contain the value of the vector-valued output function for each of the n data points
    # e.g. in case of a one-dimensional output function, the first row can be the label for each data point
    data = pd.read_csv(path, sep=',', header=None)
    for sweep in range(0,number_sweeps):
        print("Sweep number: " + str(sweep+1))
        pf_ds,pf,indices_principal_feature_values=find_relevant_principal_features(data,number_output_functions,cluster_size,alpha,min_n_datapoints_a_bin,shuffle_feature_numbers,frac)
        list_pf_ds.append(pf_ds)
        # Output the principal features related to the output function in a list where the numbers correspod to the rows of the input csv-file
        f = open("principal_features_depending_system_state"+str(sweep)+".txt", "w")
        for i in pf_ds:
            for j in i:
                f.write(str(j) + str(","))
            f.write("\n")
        f.close()
        # Output the principal features in a list where the numbers correspond to the rows of the input csv-file
        f = open("principal_features_global_indices"+str(sweep)+".txt", "w")
        for i in pf:
            for j in i:
                f.write(str(j) + str(","))
            f.write("\n")
        f.close()
        np.savetxt("global_indices_and_principal_features_state_dependency"+str(sweep)+".csv", indices_principal_feature_values,delimiter=",")
    print("Time needed for the PFA in seconds: " + str(time.time()-start_time))


    #Intersect the lists of principal features related to the output function
    #All the features corresponding to the returned subgraphs are considered in each list

    list_principal_features_depending_on_system_state_for_intersection=[]
    for i in list_pf_ds:
        intermediate_list = []
        for j in i:
            for k in j:
                if k !='*':
                    intermediate_list.append(k)
        list_principal_features_depending_on_system_state_for_intersection.append(intermediate_list)
    pf_from_intersection=list_principal_features_depending_on_system_state_for_intersection[0]
    if number_sweeps > 1:
        for i in range(1, len(list_principal_features_depending_on_system_state_for_intersection)):
            pf_from_intersection=list(set(pf_from_intersection).intersection(set(list_principal_features_depending_on_system_state_for_intersection[i])))
        f = open("principal_features_depending_system_state_intersection.txt", "w")
        for i in pf_from_intersection:
            f.write(str(i)+str(","))
        f.close()

    # Outputs a list of DataFrames where the index feature refers to the row in the csv-file.
    # The mutual information is calculated between the feature represented in the first row of the data frame and the feature referred to in the index feature column.
    # The first row is consequently the mutual information of the corresponding component of the output-function with itself
    if calculate_mutual_information==1:
        print("Calculating mutual information")
        list_data_frame_feature_mutual_information=get_mutual_information(data,number_output_functions,pf_from_intersection,min_n_datapoints_a_bin,basis_log_mutual_information)
        for i in range(0,len(list_data_frame_feature_mutual_information)):
            print(list_data_frame_feature_mutual_information[i])
        return pf_from_intersection, list_data_frame_feature_mutual_information

    return pf_from_intersection

In [ ]:
def pfa(path, number_output_functions=1, number_sweeps=1, cluster_size=50, alpha=0.01, min_n_datapoints_a_bin=500, shuffle_feature_numbers=0, frac=1, calculate_mutual_information=0, basis_log_mutual_information=2):
    # pf_ds = principal features related to output functions, pf = all principal features
    start_time=time.time()
    list_pf_ds=[]


    # The csv file's content is an m x n Matrix with m - number components of output-function = number features and n = number of data points
    # where the first number components of output-function rows contain the value of the vector-valued output function for each of the n data points
    # e.g. in case of a one-dimensional output function, the first row can be the label for each data point
    data = pd.read_csv(path, sep=',', header=None)
    for sweep in range(0,number_sweeps):
        print("Sweep number: " + str(sweep+1))
        pf_ds,pf,indices_principal_feature_values=find_relevant_principal_features(data,number_output_functions,cluster_size,alpha,min_n_datapoints_a_bin,shuffle_feature_numbers,frac)
        list_pf_ds.append(pf_ds)
        # Output the principal features related to the output function in a list where the numbers correspod to the rows of the input csv-file
        f = open("principal_features_depending_system_state"+str(sweep)+".txt", "w")
        for i in pf_ds:
            for j in i:
                f.write(str(j) + str(","))
            f.write("\n")
        f.close()
        # Output the principal features in a list where the numbers correspond to the rows of the input csv-file
        f = open("principal_features_global_indices"+str(sweep)+".txt", "w")
        for i in pf:
            for j in i:
                f.write(str(j) + str(","))
            f.write("\n")
        f.close()
        np.savetxt("global_indices_and_principal_features_state_dependency"+str(sweep)+".csv", indices_principal_feature_values,delimiter=",")
    print("Time needed for the PFA in seconds: " + str(time.time()-start_time))


    #Intersect the lists of principal features related to the output function
    #All the features corresponding to the returned subgraphs are considered in each list

    list_principal_features_depending_on_system_state_for_intersection=[]
    for i in list_pf_ds:
        intermediate_list = []
        for j in i:
            for k in j:
                if k !='*':
                    intermediate_list.append(k)
        list_principal_features_depending_on_system_state_for_intersection.append(intermediate_list)
    pf_from_intersection=list_principal_features_depending_on_system_state_for_intersection[0]
    if number_sweeps > 1:
        for i in range(1, len(list_principal_features_depending_on_system_state_for_intersection)):
            pf_from_intersection=list(set(pf_from_intersection).intersection(set(list_principal_features_depending_on_system_state_for_intersection[i])))
        f = open("principal_features_depending_system_state_intersection.txt", "w")
        for i in pf_from_intersection:
            f.write(str(i)+str(","))
        f.close()

    # Outputs a list of DataFrames where the index feature refers to the row in the csv-file.
    # The mutual information is calculated between the feature represented in the first row of the data frame and the feature referred to in the index feature column.
    # The first row is consequently the mutual information of the corresponding component of the output-function with itself
    if calculate_mutual_information==1:
        print("Calculating mutual information")
        list_data_frame_feature_mutual_information=get_mutual_information(data,number_output_functions,pf_from_intersection,min_n_datapoints_a_bin,basis_log_mutual_information)
        for i in range(0,len(list_data_frame_feature_mutual_information)):
            print(list_data_frame_feature_mutual_information[i])
        return pf_from_intersection, list_data_frame_feature_mutual_information
        
    return pf_from_intersection

In [97]:
print(inspect.getsource(find_relevant_principal_features))

NameError: name 'find_relevant_principal_features' is not defined