In [239]:
#pip install networkx
#pip install scipy
#pip install principal-feature-analysis
#pip install pandas

In [267]:
from principal_feature_analysis import pfa 
import pandas as pd

In [268]:
!pwd

/home2/lumpi/Projects/single-cell_samantha/code/scripts

# Run PFA

In [269]:
# test how the pfa read the data (somehow the label row gets processed)
path="/home2/lumpi/Projects/single-cell_samantha/data/PFA_analysis_data.csv"
data = pd.read_csv(path, sep=',', header=None)
data

,0,1,2,3,4,5,6,7,8,9,...,2512,2513,2514,2515,2516,2517,2518,2519,2520,2521
0,0.000000,0.00000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,1.817618,0.00000,1.823131,0.470256,0.880490,1.708302,2.782923,1.434641,1.293195,2.168690,...,1.903200,1.669628,3.265346,1.495282,3.178177,3.725214,2.590477,0.000000,2.887949,2.921994
2,0.000000,0.00000,0.000000,0.470256,0.000000,0.918898,0.866574,0.725636,0.842517,0.935844,...,0.761490,1.354149,0.985548,1.004410,0.000000,1.778887,1.631599,0.000000,2.027381,0.855341
3,2.106576,0.00000,0.000000,0.000000,0.000000,0.000000,0.524357,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.436336,0.414759,0.000000,0.663731,0.000000
4,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1611,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1612,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1613,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1614,0.000000,0.00000,0.712088,0.000000,0.880490,0.000000,0.000000,0.000000,0.842517,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1615,3.207734,4.12172,4.241672,4.708393,4.807613,3.530574,5.400871,4.638028,4.977564,5.008894,...,3.766632,3.608707,2.968981,2.267112,5.113210,3.927495,3.265235,4.372667,3.238389,3.905570

In [ ]:
res,mutual_information=pfa(path="/home2/lumpi/Projects/single-cell_samantha/data/PFA_analysis_data.csv", calculate_mutual_information=True,
                           cluster_size=200, min_n_datapoints_a_bin=50)

Sweep number: 1
Feature #5 has only constant values
Feature #9 has only constant values
Feature #12 has only constant values
Feature #34 has only constant values
Feature #39 has only constant values
Feature #43 has only constant values
Feature #56 has only constant values
Feature #59 has only constant values
Feature #62 has only constant values
Feature #69 has only constant values
Feature #71 has only constant values
Feature #73 has only constant values
Feature #91 has only constant values
Feature #104 has only constant values
Feature #109 has only constant values
Feature #113 has only constant values
Feature #117 has only constant values
Feature #130 has only constant values
Feature #139 has only constant values
Feature #143 has only constant values
Feature #144 has only constant values
Feature #160 has only constant values
Feature #164 has only constant values
Feature #177 has only constant values
Feature #196 has only constant values
Feature #197 has only constant values
Feature #199 has only constant values
Feature #200 has only constant values
Feature #201 has only constant values
Feature #208 has only constant values
Feature #210 has only constant values
Feature #213 has only constant values
Feature #214 has only constant values
Feature #215 has only constant values
Feature #249 has only constant values
Feature #256 has only constant values
Feature #257 has only constant values
Feature #270 has only constant values
Feature #276 has only constant values
Feature #285 has only constant values
Feature #295 has only constant values
Feature #303 has only constant values
Feature #345 has only constant values
Feature #395 has only constant values
Feature #401 has only constant values
Feature #416 has only constant values
Feature #421 has only constant values
Feature #429 has only constant values
Feature #438 has only constant values
Feature #440 has only constant values
Feature #442 has only constant values
Feature #443 has only constant values
Feature #444 has only constant values
Feature #445 has only constant values
Feature #460 has only constant values
Feature #467 has only constant values
Feature #470 has only constant values
Feature #479 has only constant values
Feature #484 has only constant values
Feature #487 has only constant values
Feature #488 has only constant values
Feature #489 has only constant values
Feature #534 has only constant values
Feature #535 has only constant values
Feature #573 has only constant values
Feature #594 has only constant values
Feature #595 has only constant values
Feature #602 has only constant values
Feature #606 has only constant values
Feature #612 has only constant values
Feature #619 has only constant values
Feature #623 has only constant values
Feature #631 has only constant values
Feature #651 has only constant values
Feature #682 has only constant values
Feature #693 has only constant values
Feature #694 has only constant values
Feature #723 has only constant values
Feature #728 has only constant values
Feature #729 has only constant values
Feature #760 has only constant values
Feature #761 has only constant values
Feature #774 has only constant values
Feature #779 has only constant values
Feature #813 has only constant values
Feature #825 has only constant values
Feature #827 has only constant values
Feature #828 has only constant values
Feature #844 has only constant values
Feature #846 has only constant values
Feature #852 has only constant values
Feature #863 has only constant values
Feature #881 has only constant values
Feature #888 has only constant values
Feature #905 has only constant values
Feature #913 has only constant values
Feature #947 has only constant values
Feature #958 has only constant values
Feature #963 has only constant values
Feature #990 has only constant values
Feature #1005 has only constant values
Feature #1022 has only constant values
Feature #1031 has only constant values
Feature #1037 has only constant values
Feature #1056 has only constant values
Feature #1060 has only constant values
Feature #1077 has only constant values
Feature #1082 has only constant values
Feature #1112 has only constant values
Feature #1115 has only constant values
Feature #1129 has only constant values
Feature #1146 has only constant values
Feature #1168 has only constant values
Feature #1208 has only constant values
Feature #1218 has only constant values
Feature #1225 has only constant values
Feature #1238 has only constant values
Feature #1243 has only constant values
Feature #1265 has only constant values
Feature #1274 has only constant values
Feature #1292 has only constant values
Feature #1313 has only constant values
Feature #1343 has only constant values
Feature #1344 has only constant values
Feature #1359 has only constant values
Feature #1362 has only constant values
Feature #1375 has only constant values
Feature #1376 has only constant values
Feature #1380 has only constant values
Feature #1392 has only constant values
Feature #1395 has only constant values
Feature #1400 has only constant values
Feature #1403 has only constant values
Feature #1414 has only constant values
Feature #1449 has only constant values
Feature #1452 has only constant values
Feature #1459 has only constant values
Feature #1465 has only constant values
Feature #1468 has only constant values
Feature #1469 has only constant values
Feature #1473 has only constant values
Feature #1482 has only constant values
Feature #1493 has only constant values
Feature #1496 has only constant values
Feature #1522 has only constant values
Feature #1532 has only constant values
Feature #1542 has only constant values
Feature #1558 has only constant values
Feature #1571 has only constant values
Feature #1573 has only constant values
Feature #1597 has only constant values
Feature #1602 has only constant values
Feature #1603 has only constant values
Feature #1611 has only constant values
Feature #1613 has only constant values
Binning done!
List of features with constant values:
[5, 9, 12, 34, 39, 43, 56, 59, 62, 69, 71, 73, 91, 104, 109, 113, 117, 130, 139, 143, 144, 160, 164, 177, 196, 197, 199, 200, 201, 208, 210, 213, 214, 215, 249, 256, 257, 270, 276, 285, 295, 303, 345, 395, 401, 416, 421, 429, 438, 440, 442, 443, 444, 445, 460, 467, 470, 479, 484, 487, 488, 489, 534, 535, 573, 594, 595, 602, 606, 612, 619, 623, 631, 651, 682, 693, 694, 723, 728, 729, 760, 761, 774, 779, 813, 825, 827, 828, 844, 846, 852, 863, 881, 888, 905, 913, 947, 958, 963, 990, 1005, 1022, 1031, 1037, 1056, 1060, 1077, 1082, 1112, 1115, 1129, 1146, 1168, 1208, 1218, 1225, 1238, 1243, 1265, 1274, 1292, 1313, 1343, 1344, 1359, 1362, 1375, 1376, 1380, 1392, 1395, 1400, 1403, 1414, 1449, 1452, 1459, 1465, 1468, 1469, 1473, 1482, 1493, 1496, 1522, 1532, 1542, 1558, 1571, 1573, 1597, 1602, 1603, 1611, 1613]
Starting principal feature analysis!
Nodes left: 1460

In [258]:
#transfor into dataframe
mutual_information=mutual_information[0]

In [259]:
mutual_information

     index feature  mutual information
0                0            0.794272
1                1            0.161720
2                3            0.007816
3                7            0.005133
4               10            0.343983
..             ...                 ...
342            720            0.670917
343            318            0.000000
344            662            0.014447
345            247            0.203145
346            529            0.090863

[347 rows x 2 columns]

In [260]:
# correct the index of mutual information
mutual_information = mutual_information.drop(mutual_information.index[0])
mutual_information

     index feature  mutual information
1                1            0.161720
2                3            0.007816
3                7            0.005133
4               10            0.343983
5               11            0.007991
..             ...                 ...
342            720            0.670917
343            318            0.000000
344            662            0.014447
345            247            0.203145
346            529            0.090863

[346 rows x 2 columns]

In [261]:
mutual_information['index feature'] = mutual_information['index feature'] - 1
mutual_information

     index feature  mutual information
1                0            0.161720
2                2            0.007816
3                6            0.005133
4                9            0.343983
5               10            0.007991
..             ...                 ...
342            719            0.670917
343            317            0.000000
344            661            0.014447
345            246            0.203145
346            528            0.090863

[346 rows x 2 columns]

In [262]:
## correct res index (not sure if necessary)
#type(res)
# Delete the first element of list 'res'
del res[0]

# Subtract 1 from each element in the list
res = [x - 1 for x in res]
res[0:5]

[0, 2, 6, 9, 10]

In [263]:
# refine the block where combining mutual information

In [264]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')
# Set index for gene_names DataFrame to match the join operation requirement
gene_names.index = range(gene_names.shape[0])  # Assuming gene_names DataFrame should match indices as given
mutual_information = mutual_information.join(gene_names, on='index feature', how='left')
mutual_information_sorted = mutual_information.sort_values(by=["mutual information"], ascending=False)

In [265]:
mutual_information_sorted.to_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_mutual_information.csv', index=False)

f = open("principal_features_for_model.txt", "w")
for i in res:
    f.write(str(i)+str(","))
f.close()

In [266]:
mutual_information_sorted.head(20)

     index feature  mutual information gene_names
238            525            0.751974      TGFBI
239            526            0.708558     SPOCK1
342            719            0.670917   SERPINE1
217            492            0.575607    ADAMTS6
206            467            0.526202      MYO10
259            570            0.490800       SOX4
285            629            0.486788     MARCKS
57             123            0.485984       NAV1
236            520            0.468442        LOX
248            547            0.449390     ADAM19
41              81            0.444531    S100A11
75             161            0.441493     MBOAT2
112            252            0.429763        FN1
314            688            0.406989     IGFBP3
242            536            0.391299       FGF1
266            586            0.376263       IER3
177            401            0.362033     IGFBP7
272            604            0.361966      VEGFA
4                9            0.343983      MFAP2
154            346            0.326507      PLOD2

## Of the gene List

In [57]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')

In [60]:
gene_names.shape

(1615, 1)

In [187]:
## ## Validate smae location of gene_names and gene name
gene_names.iloc[468]

gene_names    LINC02223
Name: 468, dtype: object

In [ ]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')

In [ ]:
### Of the PFA file

In [181]:
path="/home2/lumpi/Projects/single-cell_samantha/data/PFA_analysis_data.csv"
number_sweeps=10
gene_selection=0 # validate on PFA = 0, random genes = 1 or all genes = 2


data_total=pd.read_csv(path, sep=",", header=None).transpose()

## here read correctly
data=data_total.sample(frac = 0.8)
data_test=data_total.drop(data.index)
data=data.transpose().to_numpy()
data_test=data_test.transpose().to_numpy()
data_total

,0,1,2,3,4,5,6,7,8,9,...,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615
0,0.0,1.583742,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,3.963516
1,0.0,1.817618,0.0,2.106576,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,3.207734
2,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.291329,0.0,0.0,0.0,0.000000,4.121720
3,0.0,1.823131,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.712088,0.0,0.0,0.0,0.712088,4.241672
4,0.0,1.036066,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.646608,0.0,0.0,0.0,0.000000,4.065095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3723,1.0,3.952191,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,4.907056
3724,1.0,1.624724,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.624724,0.0,0.0,0.0,1.962280,3.515007
3725,1.0,0.896253,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.896253,0.0,0.0,0.0,0.896253,4.477613
3726,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.242907,0.0,0.0,0.0,0.000000,4.970865
3727,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,3.875414

In [189]:
data_test

array([[0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        1.        ],
       [1.43464065, 1.03139913, 1.97117901, ..., 3.17817664, 1.97004366,
        2.73304296],
       [0.72563642, 1.03139913, 0.70796478, ..., 0.        , 0.        ,
        1.16697109],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.70796478, ..., 0.        , 0.        ,
        1.16697109],
       [4.63802814, 4.78856754, 4.79134512, ..., 5.11320972, 5.61336994,
        4.75390863]])

In [186]:
df = data_total
#average_values = df.groupby(df.index).mean()
average_values = df.groupby(df.iloc[:, 0]).mean()
average_values.iloc[:, 468]  
## this position (468) is not LINC02223 but MYO10 
## assumed is when PFA tells a position the wrong gene names is assigned. 
## However the validation with this wrong assigned genne names works, indicating that the PFA alogorithm might account for the mismatch in column index)

0
0.0    0.654341
1.0    2.484578
Name: 468, dtype: float64

In [183]:
#gene_names['LINC02223']
gene_names.index[gene_names['gene_names'] == 'LINC02223'].tolist()

[468]

In [74]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')

In [ ]:
gene_names=pd.read_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_names.csv')
gene_names=gene_names.iloc[res,:].reset_index(drop=True)

mutual_information=mutual_information.join(gene_names)

mutual_information_sorted=mutual_information.sort_values(by=["mutual information"], ascending=False)
mutual_information_sorted.to_csv('/home2/lumpi/Projects/single-cell_samantha/data/gene_mutual_information.csv', index=False)

In [80]:
gene_names.iloc[res,:][200:220]

        gene_names
456         SORBS2
457        F11-AS1
462         SNHG18
463         CTNND2
465        OTULINL
466  CTD-2350J17.1
468      LINC02223
475           NPR3
476          RAI14
477          AGXT2
481      LINC00604
483      FGF10-AS1
485          ARL15
486           ESM1
490          PDE4D
491         ZSWIM6
492        ADAMTS6
493          MAST4
494          CD180
496       ARHGEF28

In [99]:
import inspect 
print(inspect.getsource(pfa))

def pfa(path, number_output_functions=1, number_sweeps=1, cluster_size=50, alpha=0.01, min_n_datapoints_a_bin=500, shuffle_feature_numbers=0, frac=1, calculate_mutual_information=0, basis_log_mutual_information=2):
    # pf_ds = principal features related to output functions, pf = all principal features
    start_time=time.time()
    list_pf_ds=[]


    # The csv file's content is an m x n Matrix with m - number components of output-function = number features and n = number of data points
    # where the first number components of output-function rows contain the value of the vector-valued output function for each of the n data points
    # e.g. in case of a one-dimensional output function, the first row can be the label for each data point
    data = pd.read_csv(path, sep=',', header=None)
    for sweep in range(0,number_sweeps):
        print("Sweep number: " + str(sweep+1))
        pf_ds,pf,indices_principal_feature_values=find_relevant_principal_features(data,number_output_functions,cluster_size,alpha,min_n_datapoints_a_bin,shuffle_feature_numbers,frac)
        list_pf_ds.append(pf_ds)
        # Output the principal features related to the output function in a list where the numbers correspod to the rows of the input csv-file
        f = open("principal_features_depending_system_state"+str(sweep)+".txt", "w")
        for i in pf_ds:
            for j in i:
                f.write(str(j) + str(","))
            f.write("\n")
        f.close()
        # Output the principal features in a list where the numbers correspond to the rows of the input csv-file
        f = open("principal_features_global_indices"+str(sweep)+".txt", "w")
        for i in pf:
            for j in i:
                f.write(str(j) + str(","))
            f.write("\n")
        f.close()
        np.savetxt("global_indices_and_principal_features_state_dependency"+str(sweep)+".csv", indices_principal_feature_values,delimiter=",")
    print("Time needed for the PFA in seconds: " + str(time.time()-start_time))


    #Intersect the lists of principal features related to the output function
    #All the features corresponding to the returned subgraphs are considered in each list

    list_principal_features_depending_on_system_state_for_intersection=[]
    for i in list_pf_ds:
        intermediate_list = []
        for j in i:
            for k in j:
                if k !='*':
                    intermediate_list.append(k)
        list_principal_features_depending_on_system_state_for_intersection.append(intermediate_list)
    pf_from_intersection=list_principal_features_depending_on_system_state_for_intersection[0]
    if number_sweeps > 1:
        for i in range(1, len(list_principal_features_depending_on_system_state_for_intersection)):
            pf_from_intersection=list(set(pf_from_intersection).intersection(set(list_principal_features_depending_on_system_state_for_intersection[i])))
        f = open("principal_features_depending_system_state_intersection.txt", "w")
        for i in pf_from_intersection:
            f.write(str(i)+str(","))
        f.close()

    # Outputs a list of DataFrames where the index feature refers to the row in the csv-file.
    # The mutual information is calculated between the feature represented in the first row of the data frame and the feature referred to in the index feature column.
    # The first row is consequently the mutual information of the corresponding component of the output-function with itself
    if calculate_mutual_information==1:
        print("Calculating mutual information")
        list_data_frame_feature_mutual_information=get_mutual_information(data,number_output_functions,pf_from_intersection,min_n_datapoints_a_bin,basis_log_mutual_information)
        for i in range(0,len(list_data_frame_feature_mutual_information)):
            print(list_data_frame_feature_mutual_information[i])
        return pf_from_intersection, list_data_frame_feature_mutual_information

    return pf_from_intersection

In [ ]:
def pfa(path, number_output_functions=1, number_sweeps=1, cluster_size=50, alpha=0.01, min_n_datapoints_a_bin=500, shuffle_feature_numbers=0, frac=1, calculate_mutual_information=0, basis_log_mutual_information=2):
    # pf_ds = principal features related to output functions, pf = all principal features
    start_time=time.time()
    list_pf_ds=[]


    # The csv file's content is an m x n Matrix with m - number components of output-function = number features and n = number of data points
    # where the first number components of output-function rows contain the value of the vector-valued output function for each of the n data points
    # e.g. in case of a one-dimensional output function, the first row can be the label for each data point
    data = pd.read_csv(path, sep=',', header=None)
    for sweep in range(0,number_sweeps):
        print("Sweep number: " + str(sweep+1))
        pf_ds,pf,indices_principal_feature_values=find_relevant_principal_features(data,number_output_functions,cluster_size,alpha,min_n_datapoints_a_bin,shuffle_feature_numbers,frac)
        list_pf_ds.append(pf_ds)
        # Output the principal features related to the output function in a list where the numbers correspod to the rows of the input csv-file
        f = open("principal_features_depending_system_state"+str(sweep)+".txt", "w")
        for i in pf_ds:
            for j in i:
                f.write(str(j) + str(","))
            f.write("\n")
        f.close()
        # Output the principal features in a list where the numbers correspond to the rows of the input csv-file
        f = open("principal_features_global_indices"+str(sweep)+".txt", "w")
        for i in pf:
            for j in i:
                f.write(str(j) + str(","))
            f.write("\n")
        f.close()
        np.savetxt("global_indices_and_principal_features_state_dependency"+str(sweep)+".csv", indices_principal_feature_values,delimiter=",")
    print("Time needed for the PFA in seconds: " + str(time.time()-start_time))


    #Intersect the lists of principal features related to the output function
    #All the features corresponding to the returned subgraphs are considered in each list

    list_principal_features_depending_on_system_state_for_intersection=[]
    for i in list_pf_ds:
        intermediate_list = []
        for j in i:
            for k in j:
                if k !='*':
                    intermediate_list.append(k)
        list_principal_features_depending_on_system_state_for_intersection.append(intermediate_list)
    pf_from_intersection=list_principal_features_depending_on_system_state_for_intersection[0]
    if number_sweeps > 1:
        for i in range(1, len(list_principal_features_depending_on_system_state_for_intersection)):
            pf_from_intersection=list(set(pf_from_intersection).intersection(set(list_principal_features_depending_on_system_state_for_intersection[i])))
        f = open("principal_features_depending_system_state_intersection.txt", "w")
        for i in pf_from_intersection:
            f.write(str(i)+str(","))
        f.close()

    # Outputs a list of DataFrames where the index feature refers to the row in the csv-file.
    # The mutual information is calculated between the feature represented in the first row of the data frame and the feature referred to in the index feature column.
    # The first row is consequently the mutual information of the corresponding component of the output-function with itself
    if calculate_mutual_information==1:
        print("Calculating mutual information")
        list_data_frame_feature_mutual_information=get_mutual_information(data,number_output_functions,pf_from_intersection,min_n_datapoints_a_bin,basis_log_mutual_information)
        for i in range(0,len(list_data_frame_feature_mutual_information)):
            print(list_data_frame_feature_mutual_information[i])
        return pf_from_intersection, list_data_frame_feature_mutual_information
        
    return pf_from_intersection

In [97]:
print(inspect.getsource(find_relevant_principal_features))

NameError: name 'find_relevant_principal_features' is not defined